// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRR6cGGaJgnIlIHPP_oKEVJVgI2dvoyw0',
    appId: '1:234455896219:web:47d404715ba84e1c81363e',
    messagingSenderId: '234455896219',
    projectId: 'learning-bloc-88715',
    authDomain: 'learning-bloc-88715.firebaseapp.com',
    storageBucket: 'learning-bloc-88715.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAi03fLziZcfDxWHPyTo5A5TN0r8rgHixI',
    appId: '1:234455896219:android:0e28f524dd6bd44081363e',
    messagingSenderId: '234455896219',
    projectId: 'learning-bloc-88715',
    storageBucket: 'learning-bloc-88715.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDa9LnhYnK23WSIuAvX05N-lt07I7vfEU',
    appId: '1:234455896219:ios:e4d9d6d0c5d3b32581363e',
    messagingSenderId: '234455896219',
    projectId: 'learning-bloc-88715',
    storageBucket: 'learning-bloc-88715.appspot.com',
    iosBundleId: 'me.sheershbhatnagar.dhvanika',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDa9LnhYnK23WSIuAvX05N-lt07I7vfEU',
    appId: '1:234455896219:ios:e4d9d6d0c5d3b32581363e',
    messagingSenderId: '234455896219',
    projectId: 'learning-bloc-88715',
    storageBucket: 'learning-bloc-88715.appspot.com',
    iosBundleId: 'me.sheershbhatnagar.dhvanika',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRR6cGGaJgnIlIHPP_oKEVJVgI2dvoyw0',
    appId: '1:234455896219:web:bc610b8b2808455181363e',
    messagingSenderId: '234455896219',
    projectId: 'learning-bloc-88715',
    authDomain: 'learning-bloc-88715.firebaseapp.com',
    storageBucket: 'learning-bloc-88715.appspot.com',
  );
}
